# Generated by Django 5.1 on 2024-08-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
