# Generated by Django 5.1 on 2024-08-20 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_product_photos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductPhoto',
        ),
    ]
