# Generated by Django 5.1 on 2024-08-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_delete_productphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photos',
            field=models.JSONField(default=list),
        ),
    ]
