# Generated by Django 5.1 on 2024-08-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_alter_product_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(default='null', upload_to='categorias_photos/'),
        ),
    ]
