# Generated by Django 5.1 on 2024-08-21 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0006_category_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(default='null', upload_to='categorias_fotos/'),
        ),
    ]
